version: 0.1

phases:
  install:
    commands:
      - echo Installing Node 18...
      - curl -sL https://deb.nodesource.com/setup_18.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm -v
      - npm install --legacy-peer-deps
      - npm config set legacy-peer-deps true
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
    - package.json
  discard-paths: no
  base-directory: build
cache:
 paths:
  - node_modules